cc_library(
    name = "elo",
    srcs = [
        "race_processor.cpp",
    ],
    hdrs = [
        "race_processor.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//base",
        "//tristats",
    ],
)
