races = db.getCollection('races')
// races.find()
// races.find({name: /Wisconsin/, date: /2002/}).sort({_id: -1})
// races.find({'$text': {'$search': 'brazil'}})
// races.find({'name': /2015 IRONMAN Lake Placid/}, {results: {'$elemMatch': {id: 'F7403766-F391-4F09-891C-C0D64D6C8512'} } })
// races.find({'name': /IRONMAN Tallinn/})
// races.count({name: ''})
// races.find({'name': 'IRONMAN 70.3 Oman', 'date': '2020-02-21'}, {results: {$slice: [1, 1]}})
races.aggregate([{'$match': {'name': 'IRONMAN 70.3 Oman', 'date': '2020-02-21'}}, {'$unwind': '$results'}, {'$sort': {'results.b': -1}}, {'$skip': 4}, {'$limit': 2}])